name: employee
description: Production-grade Flutter app for petrol pump employees to issue loyalty points
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  get_it: ^7.6.4
  injectable: ^2.4.1
  
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  
  sqflite_sqlcipher: ^2.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  
  connectivity_plus: ^5.0.2
  geolocator: ^12.0.0
  permission_handler: ^11.3.0
  
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^5.2.3
  
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  
  logger: ^2.0.2+1
  device_info_plus: ^9.1.1
  package_info_plus: ^8.0.1
  uuid: ^4.3.3
  intl: ^0.19.0
  
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  freezed: ^2.4.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
